### ISSUE TITLE
Better naming of metric

### ISSUE THREAD

**Issue by sileht** [gnocchixyz/collectd-gnocchi#16]
Most metric names end with -0, -1 or -2 that not really helpfull.

We could maintain a mapping with their meaning.

For example, disk plugin, 0 means read, 1 means write, so generated names should be:
* disk_octect_write
* disk_octect_read
* disk_ops_read
* disk_ops_write
...

**Comment by jd** [comment]
Is there a way to guess that? Sounds like a collectd issue :(

**Comment by sileht** [comment]
No you have to read source code/doc of each plugins. The collectd plugin API does expose name for each values.
