### ISSUE TITLE
Collectd metrics not creating data, cannot create directories in /home/gnocchi/tmp

### ISSUE THREAD

**Issue by fbattle** [gnocchixyz/collectd-gnocchi#25]
Hi,
I'm working on getting gnocchi setup on a single machine.  That is, to start, I want to run metrics on my own machine.  So gnocchi-api and gnocchiclient are installed on the same machine.

The machine is Oracle Linux 7, a variant of RHEL.  SELinux is present.  I opted to use apache and mod_wsgi to run gnocchi-api, I run metricd in a shell, and collected in another shell.  I can run gnocchi and see the standard metrics provided by collectd.  Just to be clear, I am able to see the collectd resource and I can see the metrics, but the actual data is not there.

The first error I see is in /var/log/messages:
```
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: ClientException: <!DOCTYPE HTML PUBLIC "-/
/IETF//DTD HTML 2.0//EN">#012<html><head>#012<title>500 Internal Server Error</title>#
012</head><body>#012<h1>Internal Server Error</h1>#012<p>The server encountered an int
ernal error or#012misconfiguration and was unable to complete#012your request.</p>#012
<p>Please contact the server administrator at #012 root@localhost to inform them of th
e time this error occurred,#012 and the actions you performed just before this error.<
/p>#012<p>More information about this error may be available#012in the server error lo
g.</p>#012</body></html>#012 (HTTP 500)
```
```
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: plugin: 2131 value lists were left after s
hutting down the write threads.
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: Traceback (most recent call last):
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: File "/usr/lib/python2.7/site-packages/col
lectd_gnocchi/__init__.py", line 79, in inner_func#012    return func(*args, **kwargs)
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: File "/usr/lib/python2.7/site-packages/col
lectd_gnocchi/__init__.py", line 227, in flush#012    self._batch(host, values)
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: File "/usr/lib/python2.7/site-packages/col
lectd_gnocchi/__init__.py", line 244, in _batch#012    measures, create_metrics=True)
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: File "/usr/lib/python2.7/site-packages/gno
cchiclient/v1/metric.py", line 236, in batch_resources_metrics_measures#012    params=
dict(create_metrics=create_metrics))
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: File "/usr/lib/python2.7/site-packages/gno
cchiclient/v1/base.py", line 41, in _post#012    return self.client.api.post(*args, **
kwargs)
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: File "/usr/lib/python2.7/site-packages/key
stoneauth1/adapter.py", line 310, in post#012    return self.request(url, 'POST', **kw
args)
Mar  8 03:49:26 scc2-4-vm21 collectd[5691]: File "/usr/lib/python2.7/site-packages/gno
cchiclient/client.py", line 52, in request#012    raise exceptions.from_response(resp,
 method)
```
A more interesting error is in /var/log/httpd/error_log
```
[:error] [pid 28878] [remote 10.133.4.21:3264]     (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
[Thu Mar 08 00:08:37.562487 2018] [:error] [pid 28878] [remote 10.133.4.21:3264]   File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
[Thu Mar 08 00:08:37.562496 2018] [:error] [pid 28878] [remote 10.133.4.21:3264]     fd = _os.open(file, flags, 0600)
[Thu Mar 08 00:08:37.562513 2018] [:error] [pid 28878] [remote 10.133.4.21:3264] OSError: [Errno 13] Permission denied: '/home/gnocchi/tmp/gnocchimjwh8u'
```

From my `gnocchi.conf` file:
```
file_basepath = /home/gnocchi
```
I'm a bit stumped on why collectd cannot create directories in under /home/gnocchi/tmp.  I tried some desperation moves, such as chmod -R 777 the /home/gnocchi, and also chown -R apache:apache and chown -R gnocchi:gnocchi.  I think these steps demonstrate I'm not entirely confident on how this all works.  I can see apache is the owning process for httpd, but I'm unclear which user account is actually writing in the /home/gnocchi directory.  Is it user gnocchi ?

So I'm looking for help to determine why I'm getting Permission denied: '/home/gnocchi/tmp/*' error message.

Thanks

**Comment by jd** [comment]
The problem is that your Apache WSGI configuration is running with a user that is now allowed to write there. Did you check if something like SELinux was not preventing that to be done?

**Comment by fbattle** [comment]
You're right, this issue is not related to collectd.  However, your suggestion is correct.  I ran aureport -a and found these entries:
`52600. 03/08/2018 19:00:51 httpd system_u:system_r:httpd_t:s0 2 dir write unconfined_u:object_r:home_root_t:s0 denied 7542746`

So I ran semanage permissive -a httpd_t
and that error went away.  

Thank you again. 
-Fred
