### ISSUE TITLE
metrics are not getting created due to ResourceAlreadyExists Error

### ISSUE THREAD

**Issue by narasimha18sv** [gnocchixyz/collectd-gnocchi#4]
http://paste.openstack.org/show/607744/

Apr 24 14:02:42 controller collectd[19953]: Unhandled python exception in write callback: ResourceAlreadyExists: Resource a1440f58-3262-52c3-a2fd-59fc1167f7c7 already exists (HTTP 409)
Apr 24 14:02:42 controller collectd[19953]: Traceback (most recent call last):
Apr 24 14:02:42 controller collectd[19953]:  File "/usr/lib/python2.7/site-packages/collectd_gnocchi/__init__.py", line 103, in write#012    self.flush(0, None)
Apr 24 14:02:42 controller collectd[19953]:  File "/usr/lib/python2.7/site-packages/collectd_gnocchi/__init__.py", line 148, in flush#012    "host": host,
Apr 24 14:02:42 controller collectd[19953]:  File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/resource.py", line 98, in create#012    data=jsonutils.dumps(resource)).json()
Apr 24 14:02:42 controller collectd[19953]:  File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/base.py", line 41, in _post#012    return self.client.api.post(*args, **kwargs)
Apr 24 14:02:42 controller collectd[19953]:  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 223, in post#012    return self.request(url, 'POST', **kwargs)
Apr 24 14:02:42 controller collectd[19953]:  File "/usr/lib/python2.7/site-packages/gnocchiclient/client.py", line 38, in request#012    raise exceptions.from_response(resp, method)
Apr 24 14:02:42 controller collectd[19953]: ResourceAlreadyExists: Resource a1440f58-3262-52c3-a2fd-59fc1167f7c7 already exists (HTTP 409)
Whenever collectd is trying to create metrics getting resource already exists error. 

http://paste.openstack.org/show/607760/
# gnocchi resource-type list
+----------------------------+-------------------------------------------------------------------------------------+
| name                       | attributes                                                                          |
+----------------------------+-------------------------------------------------------------------------------------+
| ceph_account               |                                                                                     |
| collectd                   | - host: min_length: 0 , max_length: 255 , type: string , required: True             |
| generic                    |                                                                                     |
| host                       | - host_name: min_length: 0 , max_length: 255 , type: string , required: True        |
| host_disk                  | - host_name: min_length: 0 , max_length: 255 , type: string , required: True        |
|                            | - device_name: min_length: 0 , max_length: 255 , type: string , required: False     |
| host_network_interface     | - host_name: min_length: 0 , max_length: 255 , type: string , required: True        |
|                            | - device_name: min_length: 0 , max_length: 255 , type: string , required: False     |
| identity                   |                                                                                     |
| image                      | - container_format: min_length: 0 , max_length: 255 , type: string , required: True |
|                            | - disk_format: min_length: 0 , max_length: 255 , type: string , required: True      |
|                            | - name: min_length: 0 , max_length: 255 , type: string , required: True             |
| instance                   | - image_ref: min_length: 0 , max_length: 255 , type: string , required: False       |
|                            | - host: min_length: 0 , max_length: 255 , type: string , required: True             |
|                            | - display_name: min_length: 0 , max_length: 255 , type: string , required: True     |
|                            | - flavor_id: min_length: 0 , max_length: 255 , type: string , required: True        |
|                            | - server_group: min_length: 0 , max_length: 255 , type: string , required: False    |
| instance_disk              | - instance_id: required: True , type: uuid                                          |
|                            | - name: min_length: 0 , max_length: 255 , type: string , required: True             |
| instance_network_interface | - instance_id: required: True , type: uuid                                          |
|                            | - name: min_length: 0 , max_length: 255 , type: string , required: True             |
| ipmi                       |                                                                                     |
| network                    |                                                                                     |
| stack                      |                                                                                     |
| swift_account              |                                                                                     |
| volume                     | - display_name: min_length: 0 , max_length: 255 , type: string , required: False    |
+----------------------------+-------------------------------------------------------------------------------------+

]# gnocchi resource list | grep collectd
| a1440f58-3262-52c3-a2fd-59fc1167f7c7 | collectd                   | None                             | None                             | collectd:controller.novalocal                                        | 2017-04-24T16:04:08.914698+00:00 | None     | 2017-04-24T16:04:08.914712+00:00 | None         |

**Comment by jd** [comment]
This looks weird, it seems that the call to `self.g.metric.batch_resources_metrics_measures` fails but not because the resource does not exist. Can you check what error Gnocchi returns for that call?

**Comment by narasimha18sv** [comment]
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:08:44:11 +0000] "POST /v1/resource/collectd HTTP/1.1" 409 113 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"

There is no specific error apart from these logs.

**Comment by narasimha18sv** [comment]
**gnocchi-api.log:**
controller - - [25/Apr/2017:17:25:45 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:17:25:45 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:17:25:45 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:17:25:45 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:17:25:45 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"
controller - - [25/Apr/2017:17:25:45 +0000] "POST /v1/batch/resources/metrics/measures?create_metrics=True HTTP/1.1" 400 85 "-" "keystoneauth1/2.18.0 python-requests/2.13.0 CPython/2.7.5"

**collectd logs :**
Apr 25 11:24:48 controller collectd[20819]: Unhandled python exception in write callback: BadRequest: Resource type  does not exist (HTTP 400)
Apr 25 11:24:48 controller collectd[20819]: Traceback (most recent call last):
Apr 25 11:24:48 controller collectd[20819]:  File "/usr/lib/python2.7/site-packages/collectd_gnocchi/__init__.py", line 105, in write#012    self.flush(0, None)
Apr 25 11:24:48 controller collectd[20819]:  File "/usr/lib/python2.7/site-packages/collectd_gnocchi/__init__.py", line 146, in flush#012    measures, create_metrics=True)
Apr 25 11:24:48 controller collectd[20819]:  File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/metric.py", line 166, in batch_resources_metrics_measures#012    params=dict(create_metrics=create_metrics))
Apr 25 11:24:48 controller collectd[20819]:  File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/base.py", line 41, in _post#012    return self.client.api.post(*args, **kwargs)
Apr 25 11:24:48 controller collectd[20819]:  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 223, in post#012    return self.request(url, 'POST', **kwargs)
Apr 25 11:24:48 controller collectd[20819]:  File "/usr/lib/python2.7/site-packages/gnocchiclient/client.py", line 38, in request#012    raise exceptions.from_response(resp, method)
Apr 25 11:24:48 controller collectd[20819]: BadRequest: Resource type  does not exist (HTTP 400)

**Measures sample:**
DEBUG:root:{'controller.novalocal': defaultdict(<type 'list'>, {'interface-docker0@if_errors-0': [{'timestamp': 1493141361.869685, 'value': 0L}], 'interface-docker0@if_errors-1': [{'timestamp': 1493141361.869685, 'value': 0L}], 'load@load-0': [{'timestamp': 1493141361.869685, 'value': 0.0}], 'load@load-1': [{'timestamp': 1493141361.869685, 'value': 0.01}], 'load@load-2': [{'timestamp': 1493141361.869685, 'value': 0.05}], 'memory@memory-used-0': [{'timestamp': 1493141361.869685, 'value': 235474944.0}], 'interface-eth0@if_octets-0': [{'timestamp': 1493141361.869685, 'value': 41168761279L}], 'interface-eth0@if_octets-1': [{'timestamp': 1493141361.869685, 'value': 193363788231L}], 'memory@memory-slab_unrecl-0': [{'timestamp': 1493141361.869685, 'value': 25964544.0}], 'interface-docker0@if_octets-1': [{'timestamp': 1493141361.869685, 'value': 19863575976L}], 'interface-eth0@if_packets-0': [{'timestamp': 1493141361.869685, 'value': 54426944L}], 'memory@memory-buffered-0': [{'timestamp': 1493141361.869685, 'value': 94830592.0}], 'interface-docker0@if_octets-0': [{'timestamp': 1493141361.869685, 'value': 177692971740L}], 'memory@memory-slab_recl-0': [{'timestamp': 1493141361.869685, 'value': 163627008.0}], 'interface-docker0@if_packets-0': [{'timestamp': 1493141361.869685, 'value': 13425407L}], 'interface-docker0@if_packets-1': [{'timestamp': 1493141361.869685, 'value': 25851650L}], 'memory@memory-free-0': [{'timestamp': 1493141361.869685, 'value': 126894080.0}], 'interface-eth0@if_packets-1': [{'timestamp': 1493141361.869685, 'value': 29408179L}]})}

**Comment by jd** [comment]
Which version of Gnocchi are you running?

I don't understand how you can get "BadRequest: Resource type does not exist" when posting measures.

**Comment by narasimha18sv** [comment]
I am using stable Ocata code base

**Comment by jd** [comment]
That does not mean anything, there's no "Ocata" of Gnocchi. Is it 3.0? 3.1? Did you make any chance to the code base?
