### ISSUE TITLE
Resource Not Created

### ISSUE THREAD

**Issue by bhavinajmera** [gnocchixyz/collectd-gnocchi#5]
Hi,

 When i install collectd-gnocchi and start gnocchi-metricd, gnocchi-api and collectd it doesn't create collectd resource in gnocchi. As mentioned by you I have enabled "LoadPlugin python" in collectd and created a file "collected-gnocchi.conf" and added following lines and included it in collectd.conf

```
> <plugin python="">
> Import "collectd_gnocchi"
> <module collectd_gnocchi="">
> endpoint "http://localhost:8041"
> </module>
> </plugin>
```

My gnocchi setup works with noauth.  The only resource available is generic. I see Following errors from collectd in my syslog
May 2 17:17:04 gnocchi-01 collectd[2741]: Unhandled python exception in write callback: AttributeError: 'Gnocchi' object has no attribute 'values'
May 2 17:24:54 gnocchi-01 collectd[2741]: message repeated 7631 times: [ Unhandled python exception in write callback: AttributeError: 'Gnocchi' object has no attribute 'values']

Any Help would be appreciated.

-Bhavin Ajmera

**Comment by jd** [comment]
Hi @bhavinajmera !

Do you have an error at startup? These ones seem to happen later.

**Comment by bhavinajmera** [comment]
Resource is successfully created but metrics are missing. I have check the archive-policy-rules it is 'low'. I don't see any error's on startup as documented by you I see lot of request on gnocchi-api, with http status code 400 and 409 but when I see syslog for collectd error following are the error

May  3 23:08:53 gnocchi-01 collectd[3473]: Initialization complete, entering read-loop.
May  3 23:08:54 gnocchi-01 collectd[3473]: Unhandled python exception in write callback: ResourceAlreadyExists: Resource ed65563c-3591-54cc-866a-229e729fd34b already exists (HTTP 409)
May  3 23:08:54 gnocchi-01 collectd[3473]: message repeated 3 times: [ Unhandled python exception in write callback: ResourceAlreadyExists: Resource ed65563c-3591-54cc-866a-229e729fd34b already exists (HTTP 409)]
May  3 23:08:54 gnocchi-01 collectd[3473]: Unhandled python exception in write callback: BadRequest: {u'cause': u'Unknown resources', u'detail': [{u'original_resource_id': u'gnocchi-01', u'resource_id': u'e615bb60-d6f4-5dc8-af58-d1096b854d0a'}, {u'original_resource_id': u'gnocchi-01', u'resource_id': u'e615bb60-d6f4-5dc8-af58-d1096b854d0a'}, {u'original_resource_id': u'gnocchi-01', u'resource_id': u'e615bb60-d6f4-5dc8-af58-d1096b854d0a'}, {u'original_resource_id': u'gnocchi-01', u'resource_id': u'e615bb60-d6f4-5dc8-af58-d1096b854d0a'}, {u'original_resource_id': u'gnocchi-01', u'resource_id': u'e615bb60-d6f4-5dc8-af58-d1096b854d0a'}, {u'original_resource_id': u'gnocchi-01', u'resource_id': u'e615bb60-d6f4-5dc8-af58-d1096b854d0a'}, {u'original_resource_id': u'gnocchi-01', u'resource_id': u'e615bb60-d6f4-5dc8-af58-d1096b854d0a'}, {u'original_resource_id': u'gnocchi-01', u'resource_id': u'e615bb60-d6f4-5dc8-af58-d1096b854d0a'}, {u'original_resource_id': u'gnocchi-01', u'resource_id': u'e615bb60-d6f4-5dc8-af58-d1096b854d0a'}, {u'original_resource_id': u'g
May  3 23:08:55 gnocchi-01 collectd[3473]: Unhandled python exception in write callback: ResourceAlreadyExists: Resource ed65563c-3591-54cc-866a-229e729fd34b already exists (HTTP 409)
May  3 23:11:01 gnocchi-01 collectd[3473]: message repeated 124 times: [ Unhandled python exception in write callback: ResourceAlreadyExists: Resource ed65563c-3591-54cc-866a-229e729fd34b already exists (HTTP 409)]
May  3 23:11:07 gnocchi-01 collectd[3473]: Unhandled python exception in write callback: ResourceAlreadyExists: Resource ed65563c-3591-54cc-866a-229e729fd34b already exists (HTTP 409)

**Comment by jd** [comment]
Ok this is seems to be the same bug than in #4 
I'm gonna try to reproduce it.
